require 'hyrax/specs/shared_specs/derivative_service'
require 'hyrax/specs/shared_specs/identifiers'
require 'hyrax/specs/shared_specs/indexers'
require 'hyrax/specs/shared_specs/metadata'
require 'hyrax/specs/shared_specs/hydra_works'
require 'hyrax/specs/shared_specs/workflow_method'
