# frozen_string_literal: true
# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  include ::Hyrax::FileSetBehavior
end

Hyrax::ValkyrieLazyMigration.migrating(Hyrax::FileSet, from: ::FileSet) if ENV.fetch('VALKYRIE_TRANSITION', false)
