# Generated by curation_concerns:models:install
class Collection < ActiveFedora::Base
  include ::Sufia::CollectionBehavior
  # You can replace these metadata if they're not suitable
  include Sufia::BasicMetadata
end
