inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.1
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/test_app_templates/**/*'
    - 'vendor/**/*'
    - 'lib/hyrax/specs/**/*'

Lint/ImplicitStringConcatenation:
  Exclude:
    - 'lib/generators/hyrax/**/*'

Metrics/LineLength:
  Max: 200

Metrics/AbcSize:
  Max: 28

Metrics/MethodLength:
  Max: 15

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/MethodMissing:
  Exclude:
    - 'app/models/concerns/hyrax/file_set/characterization.rb'

Style/NumericPredicate:
  Exclude:
    - 'app/controllers/concerns/hyrax/file_sets_controller_behavior.rb'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/ZeroLengthPredicate:
  Exclude:
    - 'app/controllers/concerns/hyrax/file_sets_controller_behavior.rb'

Rails:
  Enabled: true

Rails/OutputSafety:
  Exclude:
    - 'spec/views/hyrax/my/_list_works.html.erb_spec.rb'
    - 'app/helpers/hyrax/hyrax_helper_behavior.rb'
    - 'app/helpers/hyrax/collections_helper.rb'
    - 'app/helpers/hyrax/content_block_helper_behavior.rb'
    - 'app/builders/hyrax/form_builder.rb'
    - 'app/helpers/hyrax/citations_behaviors/formatters/apa_formatter.rb'
    - 'app/helpers/hyrax/citations_behaviors/formatters/chicago_formatter.rb'
    - 'app/helpers/hyrax/citations_behaviors/formatters/mla_formatter.rb'
    - 'app/presenters/hyrax/presents_attributes.rb'
    - 'app/renderers/hyrax/renderers/attribute_renderer.rb'

Rails/DynamicFindBy:
  Enabled: false

Rails/FilePath:
  Exclude:
    - 'spec/abilities/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/abilities/**/*'
    - 'spec/config/hyrax_events_spec.rb'
    - 'spec/conversions/**/*'
    - 'spec/features/**/*'
    - 'spec/inputs/**/*'
    - 'spec/javascripts/jasmine_spec.rb'
    - 'spec/tasks/rake_spec.rb'
    - 'spec/views/**/*'

# By default RSpec/MessageSpies has the following:
#   Prefer have_received for setting message expectations. Setup form as a spy using allow or instance_spy.
# The default assumes EnforcedStyle is 'have_received'. Most of our specs are 'receive'
RSpec/MessageSpies:
  Enabled: false

RSpec/InstanceVariable:
  Exclude:
    - 'spec/services/hyrax/derivative_service_spec.rb'

RSpec/ExpectActual:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
