# nurax-pg uses Hydra::RoleManagement for user and role definition.  The following
# examples show how to perform common setup actions.
#
# @see https://github.com/samvera/hydra-role-management
#
# Create admin role
#
#   admin_role = Role.find_or_create_by(name: 'admin')
#
# Create a user
#
#   admin_user = User.find_or_create_by(email: 'user@example.com') do |user|
#     user.password = 'change_me'
#     user.password_confirmation = 'change_me'
#     user.confirmed_at = DateTime.now
#   end
#   admin_user.roles << admin_role unless admin_user.roles.include?(admin_role)
#   admin_user.save!(validate: false)
#
# You can create non-admin roles and assign users to those roles using a similar pattern.
#
# The following roles might be used for testing, so they remain here.  They will not
# be available for use when logged in through the browser.
#
development:
  archivist:
    - archivist1@example.com

test:
  archivist:
    - archivist1@example.com
    - archivist2@example.com
    - leland_himself@example.com
  admin_policy_object_editor:
    - archivist1@example.com
  donor:
    - donor1@example.com
    - leland_himself@example.com
  researcher:
    - archivist1@example.com
    - researcher1@example.com
  patron:
    - patron1@example.com
    - leland_himself@example.com

production:
  admin:
    - systems@curationexperts.com
