development:
  url: <%= ENV['SOLR_DEVELOPMENT_URL'] || ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/koppie" %>
test: &test
  url: <%= ENV['SOLR_TEST_URL'] || ENV['SOLR_URL'] || "http://127.0.0.1:#{ENV.fetch('SOLR_TEST_PORT', 8985)}/solr/koppie-test" %>
production:
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/koppie-prod" %>