# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:collection_resource CollectionResource`

attributes:
  description:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "description_tesim"
  creator:
    type: string
    multiple: true
    form:
      required: false
      primary: false
    index_keys:
      - "creator_tesim"
  rights_statement:
    type: string
    multiple: true
    form:
      primary: false
  abstract:
    type: string
    multiple: true
    form:
      primary: false
  access_right:
    type: string
    multiple: true
    form:
      primary: false
  alternative_title:
    type: string
    multiple: true
    form:
      primary: false
  based_near:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "based_near_sim"
      - "based_near_tesim"
  bibliographic_citation:
    type: string
    multiple: true
  contributor:
    type: string
    multiple: true
    form:
      primary: false
  date_created:
    type: date_time
    multiple: true
    form:
      primary: false
    index_keys:
      - "date_created_tesim"
  identifier:
    type: string
    multiple: true
    form:
      primary: false
  import_url:
    type: string
  keyword:
    type: string
    multiple: true
    index_keys:
      - "keyword_sim"
      - "keyword_tesim"
    form:
      primary: false
  publisher:
    type: string
    multiple: true
    form:
      primary: false
  label:
    type: string
    form:
      primary: false
  language:
    type: string
    multiple: true
    form:
      primary: false
  license:
    type: string
    multiple: true
    form:
      primary: false
  relative_path:
    type: string
  related_url:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "related_url_tesim"
  resource_type:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "resource_type_sim"
      - "resource_type_tesim"
  rights_notes:
    type: string
    multiple: true
    form:
      primary: false
  source:
    type: string
    multiple: true
    form:
      primary: false
  subject:
    type: string
    multiple: true
    index_keys:
      - "subject_sim"
      - "subject_tesim"
    form:
      primary: false
