---
attributes:
  redirects:
    type: hash
    multiple: true
    form:
      display: false
    view:
      admin_only: true
      render_term: redirects_path
      render_as: redirects_label
      html_dl: true
    predicate: http://samvera.org/ns/hyku/redirects
    mappings:
      simple_dc_pmh: ~
