# This config is compatible with the Bitnami nginx helm chart, while allowing us to use updated nginx Docker images.
# We previously used the Bitnami helm chart with the Bitnami Docker image; however
# Bitnami is no longer releasing new free versions of its nginx Docker images
worker_processes  auto;

error_log  /opt/bitnami/nginx/logs/error.log warn;
pid        /tmp/nginx.pid;

events {
    worker_connections  1024;
}

http {
    proxy_temp_path /tmp/proxy_temp;
    client_body_temp_path /tmp/client_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    access_log  /opt/bitnami/nginx/logs/access.log;

    sendfile        on;
    keepalive_timeout  65;

    include /opt/bitnami/nginx/conf/server_blocks/*.conf;
}
