source 'https://rubygems.org'

gem 'rails', '3.2.6'

gem 'sqlite3'

gem 'devise'
gem 'blacklight'
gem 'hydra-access-controls', :path=>'../../../hydra-access-controls'
gem 'hydra-core', :path=>'../../', :require=>'hydra-core'
gem 'rspec-rails'
gem 'factory_girl_rails', "<2.0.0" # >=2.0.0 requires ruby 1.9
