source 'https://rubygems.org'

gem 'rails', '3.2.11'

gem 'sqlite3'

gem 'devise'
gem 'blacklight'
gem 'hydra-access-controls', :path=>'../../../hydra-access-controls'
gem 'hydra-core', :path=>'../../', :require=>'hydra-core'
gem 'rspec-rails'
gem 'factory_girl_rails'
