# This Gemfile comes from hydra-head/test_support/etc/Gemfile
# It's copied into the hydra-head test app by the rake hyhead:setup_test_app task

source 'http://rubygems.org'

gem "rails", '~> 3.2.2'

gem 'sqlite3'

gem 'blacklight', '~>3.3.0'

gem 'therubyracer' # For compiling js - needed on the ci server

gem 'hydra-head', :path => '../../'
gem 'devise'
gem 'jettywrapper'

# For testing
group :development, :test do 
       gem 'rspec-rails'
       gem 'mocha'
       gem 'cucumber-rails', :require => false
       gem 'capybara'
       gem 'factory_girl', '~> 2.6.0'
       gem 'rest-client'
       gem 'solrizer-fedora', '>=1.2.5'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.4'
  gem 'coffee-rails', '~> 3.2.2'
  gem 'uglifier', '>= 1.2.3'
  gem 'jquery-rails', '>= 1.0.12'
end

