source 'https://rubygems.org'

gem 'rails', '3.2.13'

gem 'sqlite3'

gem 'devise' #BL adds this later, so check to see if we can remove this
gem 'blacklight'
gem 'hydra-head'
gem 'hydra-batch-edit', git:'git@github.com:psu-stewardship/hydra-batch-edit.git', ref:'145438859ca013d3b2584bc3c1c934c73c8d2663'


gem 'sufia', :path=>'../../'
gem 'rspec-rails', :group=>:test
gem 'capybara', :group=>:test

gem 'factory_girl'

group :assets do
  gem 'sass-rails', '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'jquery-rails'
  gem 'font-awesome-sass-rails'
end
