source 'https://rubygems.org'

gem 'rails', '3.2.9'

gem 'sqlite3'

gem 'devise'
gem 'blacklight'

gem "hydra-head"


gem 'sufia', :path=>'../../'
gem 'rspec-rails', :group=>:test
gem 'capybara', :group=>:test

gem 'factory_girl'

group :assets do
gem 'sass-rails', '~> 3.2.0'
gem 'compass-rails', '~> 1.0.0'
gem 'compass-susy-plugin', '~> 0.9.0'
end
