# -*- encoding : utf-8 -*-
require 'rails/generators'

class Sufia::Upgrade600Generator < Rails::Generators::Base

  source_root File.expand_path('../templates', __FILE__)

  desc """
This generator for upgrading sufia to 6.0 makes the following changes to your application:
 1. Adds Sufia::SearchBuilder to SearchBuilder
       """

  def insert_builder
    insert_into_file 'app/models/search_builder.rb', after: /include Blacklight::Solr::SearchBuilderBehavior/ do
      # First line should be generated by Hydra. projecthydra/hydra-head#255
      "\n  include Hydra::AccessControlsEnforcement" +
      "\n  include Sufia::SearchBuilder\n"
    end
  end

  def migrations
    generate "sufia:models:upgrade600"
  end

end

