source "http://rubygems.org"

# Specify gem dependencies in hydra-core.gemspec
gemspec

group :test do
  gem 'cucumber-rails', '>=1.2.0', :require=>false
  gem 'rcov', :platform => :mri_18
  gem 'simplecov', :platform => :mri_19
  gem 'simplecov-rcov', :platform => :mri_19
end

