Feature: As an authenticate and authorized
  user when viewing my dashboard I see all 
  the objects I have access to 

  Scenario: I am on the homepage and want to upload
    Given I am logged in as "contentauthor@psu.edu"
    And I follow "my dashboard" 
    When I press "upload_file"
    Then I should see "Upload Files"

  Scenario: I am on the homepage
    Given I am logged in as "contentauthor@psu.edu"
    And I follow "my dashboard" 
    Then I should see "Browse"
#    And I should see "Creator"
#    And I should see "Contributor"
#    And I should see "Title"
#    And I should see "Creator"
#    And I should see "Date Created"
#    And I should see "Date Published"
#    And I should see "Format"
#    And I should see "Type"
#    And I should see "Collection"
#    And I should see "Selected Items"
#    And I should see "Search History"
#    And I should see "Sort by:"
#    And I should see "Show:"
#    And I should see "per page"
#    And I should see "Name"
#    And I should see "ID"
#    And I should see "Date Created"
#    And I should see "Owner"

   Scenario: Upload a file, with metadata and check facets
    Given I am logged in as "contentauthor@psu.edu"
    When I am on the "ingest" page 
    And I attach the file "test_support/fixtures/image.jp2" to "Filedata[]"
    And I fill in "contributor1" for "generic_file_contributor" 
    And I fill in "Dan Ran" for "generic_file_creator"
    And I fill in "Dan's Book" for "generic_file_title"
    And I fill in "4/16/2012" for "generic_file_date_created"
    And I fill in "abc123" for "generic_file_tag"
    And I fill in "publisher1" for "generic_file_publisher"
    And I fill in "subject1" for "generic_file_subject"
    And I fill in "State College" for "generic_file_based_near"
    And I press "Upload"
    Then I should see "The file image.jp2 has been saved"
    And I follow "my dashboard"     
    Then I should see "Browse"
    Then I should see "Contributor"
    Then I should see "contributor1"
    Then I should see "Date Created"
    Then I should see "4/16/2012"
    Then I should see "Tag"
    Then I should see "abc123"
    Then I should see "Publisher"
    Then I should see "publisher1"
    Then I should see "Subject"
    Then I should see "subject1"
    Then I should see "Based Near"
    Then I should see "State College"
