# Generated by hyrax:models
class Collection < Valkyrie::Resource
  include ::Hyrax::CollectionBehavior
  # You can replace these metadata if they're not suitable
  include Hyrax::BasicMetadata
  # self.indexer = Hyrax::CollectionWithBasicMetadataIndexer
end
