name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          detached: true

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: samvera-labs/helm-oci-charts-releaser@main
        with:
          oci_registry: ghcr.io/samvera
          oci_username: samvera
          oci_password: ${{ secrets.GITHUB_TOKEN }}
          oci_path: charts
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_name_pattern: "{chartName}-chart"
